# Generated by Django 3.1 on 2020-08-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20200815_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.AddField(
            model_name='doctor',
            name='depart',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.doctor'),
        ),
    ]
