# Generated by Django 3.1 on 2020-08-14 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20200814_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.department', unique=models.CharField(max_length=100)),
        ),
    ]
