# Generated by Django 3.1 on 2020-08-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_auto_20200816_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('1', 'Anaestheolgy'), ('2', 'ENT')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
