# Generated by Django 3.1 on 2020-08-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_auto_20200816_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='added_on',
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default=1),
        ),
    ]
