# Generated by Django 3.1 on 2020-08-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_doctor_hospital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name']},
        ),
    ]
