# Generated by Django 3.1 on 2020-09-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_auto_20200902_2324'),
        ('categories', '0016_auto_20200903_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hospital',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ManyToManyField(to='hospital.Hospital'),
        ),
    ]
