# Generated by Django 3.1 on 2020-08-16 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0012_auto_20200816_0515'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_problem_description', models.TextField(max_length=500)),
                ('upload_prescription_photo', models.ImageField(blank=True, upload_to='')),
                ('medicines_taken', models.TextField(max_length=200, null=True)),
                ('fixed_appointment', models.BooleanField(default=False)),
                ('appointment_time', models.DateTimeField(default=None)),
                ('date_posted', models.DateField(auto_now=True)),
                ('doctor_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.doctor')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
