# Generated by Django 3.1 on 2020-09-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '__first__'),
        ('hospital', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentication_token', models.CharField(max_length=200)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_problem_description', models.TextField(max_length=500)),
                ('medicines_taken', models.TextField(max_length=200, null=True)),
                ('fixed_appointment', models.BooleanField(default=False)),
                ('appointment_date', models.DateField(default=None, null=True)),
                ('appointment_time', models.TimeField(default=None, null=True)),
                ('date_posted', models.DateField(auto_now=True)),
                ('doctor_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.doctor')),
                ('select_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
    ]
