# Generated by Django 3.1 on 2020-09-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20200906_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='authentication_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
