# Generated by Django 3.1 on 2020-09-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20200906_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='authentication_token',
        ),
    ]
