# Generated by Django 3.1 on 2020-09-01 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20200901_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 1, 8, 20, 56, 694612, tzinfo=utc)),
        ),
    ]
