# Generated by Django 3.1 on 2020-09-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_authentication_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='authentication_token',
        ),
    ]
