# Generated by Django 3.1 on 2020-09-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_auto_20200901_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='upload_prescription_photo',
        ),
    ]
