# Generated by Django 3.1 on 2020-09-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_auto_20200901_0932'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient_name', 'appointment_date', 'appointment_time')},
        ),
    ]
