# Generated by Django 3.1 on 2020-09-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_auto_20200901_0932'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
