# Generated by Django 3.1 on 2020-09-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_auto_20200901_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(error_messages={'required': 'Please let us know what to call you!'}, max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_problem_description',
            field=models.TextField(error_messages={'required': 'Please describe Your Problem'}, max_length=500),
        ),
    ]
