# Generated by Django 3.1 on 2020-09-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_auto_20200901_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(error_messages={'required': 'Please Enter Name'}, max_length=200),
        ),
    ]
