# Generated by Django 3.1 on 2020-09-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_auto_20200901_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(error_messages={'blank': 'Enter Name', 'null': 'Provide us your Name'}, max_length=200),
        ),
    ]
