# Generated by Django 3.1 on 2020-09-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0023_appointment_select_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='select_hospital',
            field=models.CharField(default='', max_length=200),
        ),
    ]
