# Generated by Django 3.1 on 2020-09-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0024_auto_20200901_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='select_hospital',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
