# Generated by Django 3.1 on 2020-09-01 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_merge_20200831_0350'),
        ('appointment', '0026_auto_20200901_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='select_hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
