# Generated by Django 3.1 on 2020-09-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0027_auto_20200901_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='authentication_token',
            field=models.CharField(default='121', max_length=200),
        ),
    ]
