# Generated by Django 3.1 on 2020-08-31 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_hospital_doctors'),
        ('hospital', '0003_auto_20200821_2309'),
    ]

    operations = [
    ]
