# Generated by Django 3.1 on 2020-09-04 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0011_auto_20200903_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
