# Generated by Django 3.1 on 2020-09-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_model',
            name='post_at',
            field=models.DateField(),
        ),
    ]
