# Generated by Django 2.2 on 2020-08-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_model',
            name='post_at',
            field=models.DateField(),
        ),
    ]
