# Generated by Django 3.1 on 2020-09-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('notice', '0002_auto_20200912_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_model',
            name='hospital',
            field=models.ManyToManyField(null=True, to='hospital.Hospital'),
        ),
    ]
