# Generated by Django 3.1 on 2020-08-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_auto_20200828_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pictures',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
