# Generated by Django 3.1 on 2020-08-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_auto_20200828_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_hospital',
            field=models.BooleanField(default=False),
        ),
    ]
