# Generated by Django 3.1 on 2020-08-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_auto_20200829_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pictures',
            field=models.ImageField(blank=True, default='noimage.jpg', upload_to=''),
        ),
    ]
