# Generated by Django 3.1 on 2020-08-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_auto_20200830_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
